version: "3"

volumes:
  todo-db-store:

services:
  php:
    container_name: ${PROJECT_NAME}-php
    build:
      args:
        PHP_VER: ${PHP_VER}
      context: ./php
    ports:
      - ${PHP_PORT}:8000
      - 9515:9515
    working_dir: ${WORKING_DIR}
    volumes:
      - ${PROJECT_PATH}:${WORKING_DIR}
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}

  nginx:
    depends_on:
      - php
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:${NGINX_VER}-alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${PROJECT_PATH}:${WORKING_DIR}
      - ./nginx/logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - php

  mysql:
    depends_on:
      - php
    container_name: ${PROJECT_NAME}-mysql
    image: mysql:${MYSQL_VER}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - todo-db-store:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpadmin:
    container_name: ${PROJECT_NAME}-phpadmin
    image: phpmyadmin/phpmyadmin:5.0
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    links:
      - mysql

  node:
    container_name: ${PROJECT_NAME}-node
    image: node:${NODE_VER}-alpine
    tty: true
    working_dir: ${WORKING_DIR}
    volumes:
      - ${PROJECT_PATH}:${WORKING_DIR}
